In [1]:
path="../input/processed-dataset/"

In [2]:
import pandas as pd
import numpy as np

In [3]:
train=pd.read_csv(path+"train.csv")
data=pd.read_csv(path+"preprocessed_data.csv")

In [4]:
labels=train.iloc[:,2:]
labels.head(10)

toxic  severe_toxic  obscene  threat  insult  identity_hate
0      0             0        0       0       0              0
1      0             0        0       0       0              0
2      0             0        0       0       0              0
3      0             0        0       0       0              0
4      0             0        0       0       0              0
5      0             0        0       0       0              0
6      1             1        1       0       1              0
7      0             0        0       0       0              0
8      0             0        0       0       0              0
9      0             0        0       0       0              0

In [5]:
classes=list(labels.columns)
classes

['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

In [6]:
y=[]
for idx,row in labels.iterrows():
    y.append(row.values)
y=np.array(y)

In [9]:
data.head()

Unnamed: 0                id  \
0           0  0000997932d777bf   
1           1  000103f0d9cfb60f   
2           2  000113f07ec002fd   
3           3  0001b41b1c6bb37e   
4           4  0001d958c54c6e35   

                                        comment_text  toxic  severe_toxic  \
0  Explanation\nWhy the edits made under my usern...      0             0   
1  D'aww! He matches this background colour I'm s...      0             0   
2  Hey man, I'm really not trying to edit war. It...      0             0   
3  "\nMore\nI can't make any real suggestions on ...      0             0   
4  You, sir, are my hero. Any chance you remember...      0             0   

   obscene  threat  insult  identity_hate  \
0        0       0       0              0   
1        0       0       0              0   
2        0       0       0              0   
3        0       0       0              0   
4        0       0       0              0   

                                              vector  
0  [ 0.00593334  0.07003178 -0.2012667   0.377534...  
1  [-0.2508106   0.01673899  0.31538136 -0.121969...  
2  [ 0.41935966 -0.12742983 -0.48621123  0.245375...  
3  [ 0.32448252 -0.40889367 -0.00564199  0.136562...  
4  [-0.04981409  0.68221519 -0.62567751  0.101100...

In [15]:
type(data['vector'][0])

str

In [28]:
def vec(string):
    string = string.replace('\n', '')
    string = string.replace('[ ', '')
    string = string.replace('[', '')
    string = string.replace(']', '')
    lst = string.split()
    for i in range(len(lst)):
        lst[i] = float(lst[i])
    return lst

In [29]:
lst = []
for ele in data['vector']:
    lst.append(vec(ele))

In [32]:
x = np.array(lst)
x.shape

(159571, 100)

In [39]:
from sklearn.naive_bayes import GaussianNB
from sklearn.multiclass import OneVsRestClassifier

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(x,y,test_size=0.2,random_state=1)

In [35]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [40]:
model = GaussianNB()

train_acc = []
val_acc = []

preds_train = []
preds_val = []

f1_val = []

for i, label_name in enumerate(classes):
    print('Class: ',label_name)
    model.fit(X_train,y_train[:,i])
  
    preds_train_class = model.predict(X_train)
    train_acc_class = accuracy_score(y_train[:,i], preds_train_class)
    print('Train Accuracy:', train_acc_class)
    train_acc.append(train_acc_class)
    preds_train.append(preds_train_class)

    preds_val_class = model.predict(X_val)
    val_acc_class = accuracy_score(y_val[:,i], preds_val_class)
    print('Val Accuracy:', val_acc_class)
    val_acc.append(val_acc_class)
    preds_val.append(preds_val_class)

    cm = confusion_matrix(y_val[:,i], preds_val_class)
    print(cm)

    tn, fp, fn, tp = cm.ravel()
    precision= tp/(tp+fp+1e-5)
    recall= tp/(tp+fn+1e-5)
    f1_score= (2*precision*recall)/(precision+recall+1e-5)
    print('precision {:.4f} recall {:.4f} F1 score {:.4f}:'.format(precision,recall,f1_score))
    f1_val.append(f1_score)

    print()
    
print('mean train accuracy : ', np.mean(train_acc))
print('mean val accuracy :', np.mean(val_acc))
print('mean val F1 score :', np.mean(f1_val))

Class:  toxic
Train Accuracy: 0.9047753337093438
Val Accuracy: 0.9069716434278552
[[26569  2243]
 [  726  2377]]
precision 0.5145 recall 0.7660 F1 score 0.6156:

Class:  severe_toxic
Train Accuracy: 0.9611455787428714
Val Accuracy: 0.9610841297195676
[[30416  1196]
 [   46   257]]
precision 0.1769 recall 0.8482 F1 score 0.2927:

Class:  obscene
Train Accuracy: 0.936783229930438
Val Accuracy: 0.9369262102459659
[[28621  1607]
 [  406  1281]]
precision 0.4436 recall 0.7593 F1 score 0.5600:

Class:  threat
Train Accuracy: 0.9310569029266152
Val Accuracy: 0.9325082249725835
[[29679  2135]
 [   19    82]]
precision 0.0370 recall 0.8119 F1 score 0.0707:

Class:  insult
Train Accuracy: 0.9297408660775835
Val Accuracy: 0.9306282312392292
[[28474  1867]
 [  347  1227]]
precision 0.3966 recall 0.7795 F1 score 0.5257:

Class:  identity_hate
Train Accuracy: 0.9315034154289653
Val Accuracy: 0.9314115619614601
[[29498  2131]
 [   58   228]]
precision 0.0967 recall 0.7972 F1 score 0.1724:

mean train